//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblArac()
        {
            this.TblSozlesme = new HashSet<TblSozlesme>();
        }
    
        public int AracID { get; set; }
        public string Plaka { get; set; }
        public string Marka { get; set; }
        public string Seri { get; set; }
        public Nullable<int> Yil { get; set; }
        public string Renk { get; set; }
        public Nullable<int> Kilometre { get; set; }
        public string YakitTuru { get; set; }
        public Nullable<decimal> GunlukKiraUcreti { get; set; }
        public string Resim { get; set; }
        public string Tarih { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSozlesme> TblSozlesme { get; set; }
    }
}
